server:
  port: 8084
spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://pos-products
          predicates:
            - Path=/products/**
        - id: carts
          uri: lb://pos-carts
          predicates:
            - Path=/carts/**
        - id: orders
          uri: lb://pos-orders
          predicates:
            - Path=/orders/**
        #- id: delivery
        #  uri: lb://pos-delivery
        #  predicates:
        #    - Path=/delivery/**

